---
title: "Rock Nitrogen"
author: "Rebecca Martinez"
date: "November 14, 2025"
output:
  pdf_document:
    toc: true
  html_document:
    toc: true
---

```{r setup, include=FALSE}
# Set global options for all chunks
knitr::opts_chunk$set(
  echo = FALSE,     # hide code
  warning = FALSE,  # hide warnings
  message = FALSE,  # hide messages
  error = FALSE     # hide errors
)

#install.packages("tidyverse")
#install.packages("gt")
#install.packages("flextable")
#intall.packages("janitor")
#install.packages("cowplot")
library(tidyverse)
library(janitor) #clean data 
library(gt)
library(flextable)
library(cowplot) # plots into objects, insert objects to make grid

```

```{r data cleaning}

# Load and clean data
rock_nitrogen <- read_csv("data_raw/rock_samples_SIF_results.csv")  |> 
  clean_names()

rock_n_full <- rock_nitrogen |> 
  mutate(across(where(is.character),
                ~ str_squish(.)  |> 
                  str_replace_all(" ", "_")  |> 
                  tolower()
                )) |> 
  mutate(
    soaked = case_when(
      str_detect(sample_id, "-p-") ~ "yes",
      str_detect(sample_id, "-n-") ~ "no",
      TRUE ~ NA
    ),
    sample_name = str_extract(sample_id, "(.*)-[pn]-", group = 1),
    location = if_else(str_detect(sample_name, "p1"), "Sedgwick", "SCI")
  ) %>%
  filter(sample_name != "ref_soil", sample_name != "sci-blue-schist", rock_type != "rincon_shale", sample_name != "brncp1")


  






# Riley's N sample 

riley_rock_n <- read_csv(("data_raw/rileyh_n_data.csv"))


riley_n_clean <- riley_rock_n |> 
  rename(n_ppm = "nitrogen_ppm") |> 
  mutate(across(where(is.character), ~ str_to_lower(.)),
         location = "SCI",
         sample_name = sample_id,
         base_sample = str_replace(sample_name, "-[0-9]+$", "") ) |> 
          filter(rock_type != "rincon_shale")



# removing non soaked samples

n_rock_full <- rock_n_full |> 
  filter(soaked != "no")
  

merged_n <- bind_rows(
  riley_n_clean|> 
    select(sample_id, rock_type, n_ppm, location, sample_name),
  n_rock_full |>  
    select(sample_id, rock_type, n_ppm, location, sample_name)
) |>   
  rename(rock_labels = rock_type)


#new rock names column


lithology <- c(
  "gabbro_diorite"                   = "Gabbro–Diorite",
  "jolla_viejo_formation_sandstone" = "Sandstone (Tjv)",
  "jolla_viejo_formation"           = "Sandstone (Tjv)",
  "older_alluvium"                  = "Alluvium (Qoa)",
  "vaqueros_formation_sandstone"    = "Sandstone (Tvs)",
  "vaqueros_formation_conglomerate" = "Conglomerate (Tvs)",
  "monterey_formation"              = "Mudstone/Shale (Tmo)",
  "tuff"                            = "Tuff (Ttu)",
  "cozy_dell_shale"                 = "Shale (Tcd)",
  "rincon_shale"                    = "Shale (Trn)",
  "shale"                           = "Shale (Tr)",
  "greenstone"                      = "Greenstone (Jsv)",
  "serpentine"                      = "Serpentinite (Jsp)",
  "sci_schist"                      = "Schist",
  "schist_from_conglomerate"        = "Test Schist"
)


rock_class_map <- c(
  "gabbro_diorite"                   = "Igneous",
  "jolla_viejo_formation_sandstone" = "Sedimentary",
  "jolla_viejo_formation"           = "Sedimentary",
  "older_alluvium"                  = "Sedimentary",
  "vaqueros_formation_sandstone"    = "Sedimentary",
  "vaqueros_formation_conglomerate" = "Sedimentary",
  "monterey_formation"              = "Sedimentary",
  "tuff"                            = "Sedimentary",
  "cozy_dell_shale"                 = "Sedimentary",
  "rincon_shale"                    = "Sedimentary",
  "shale"                           = "Sedimentary",
  "greenstone"                      = "Metamorphic",
  "serpentine"                      = "Ultramafic",
  "sci_schist"                      = "Metamorphic",
  "schist_from_conglomerate"        = "Metamorphic"
)



merged_n_full <- merged_n |> 
  mutate(
    lithology = recode(rock_labels, !!!lithology),
    rock_class = recode(rock_labels, !!!rock_class_map))
  


```


#


## Boxplot of Nitrogen Values

This boxplot shows the distribution of nitrogen per rock type, separated by location.

```{r visual 5}


# Boxplot of nitrogen by rock_type and soaked, faceted by location
ggplot(rock_n_full, aes(x = rock_type, y = n_ppm, fill = soaked)) +
  geom_boxplot() +
  facet_wrap(~ location) +
  labs(
    x = "Rock Type",
    y = "Nitrogen (ppm)",
    fill = NULL
  ) +
  theme_classic() +
  theme(
    panel.background = element_rect(fill = "gray95", color = "black"),
    axis.text.x = element_text(angle = 45, hjust = 1)
  )

# simplified rock type with reference in parentheses:
# sandstone (Tv)
# shale (Tcd)
# sandstone (Tjv)
# 
# 
# 
# 
ggplot(merged_n, aes(x = rock_type, y = n_ppm, fill = location)) +
  geom_boxplot() +
  labs(
    x = "Rock Type",
    y = "Nitrogen (ppm)",
    fill = NULL
  ) +
  theme_classic() +
  theme(
    panel.background = element_rect(fill = "gray95", color = "black"),
    axis.text.x = element_text(angle = 45, hjust = 1)
  )
#
#
```



```{r merged N}


location_colors <- c(
  "SCI" = "#386641",      # deep green
  "Sedgwick" = "orange4"  # brown-orange
)
 
ggplot(merged_n_full, aes(x = lithology, y = n_ppm, fill =  rock_class )) +
  geom_boxplot(position = position_dodge(width = 0.7))+
  facet_wrap(~ location, scales = "free_x") +
  labs(
    x = "Lithology",
    y = "Nitrogen (ppm)",
    fill = "Location"
  ) +
  theme_bw() +
  theme(
    panel.background = element_rect(color = "black"),
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.position = c(0.2, 0.8),
    strip.text = element_text(face = "bold", size = 12)
  )

ggplot(merged_n_full, aes(x = lithology, y = n_ppm, fill = location)) +
  geom_boxplot(position = position_dodge(width = 0.7)) +
   scale_fill_manual(values = location_colors,
                    labels = c("SCI" = "Santa Cruz Island",
                               "sedgwick" = "Sedgwick")) +
  labs(
    x = "Lithology",
    y = "Nitrogen (ppm)",
    fill = "Location") +
    theme_classic(base_size = 16)+
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1, size = 11, face = "bold"),
    legend.position = c(0.2, 0.9),
    strip.text = element_text(face = "bold", size = 10),
    axis.title.x = element_blank(),
    legend.title = element_blank()
  )


```


Table

```{r}


lithology <- c(
  "gabbro_diorite"                   = "Gabbro–Diorite",
  "jolla_viejo_formation_sandstone" = "Sandstone (Tjv)",
  "jolla_viejo_formation"           = "Sandstone (Tjv)",
  "older_alluvium"                  = "Alluvium (Qoa)",
  "vaqueros_formation_sandstone"    = "Sandstone (Tvs)",
  "vaqueros_formation_conglomerate" = "Conglomerate (Tvs)",
  "monterey_formation"              = "Mudstone/Shale (Tmo)",
  "tuff"                            = "Tuff (Ttu)",
  "cozy_dell_shale"                 = "Shale (Tcd)",
  "rincon_shale"                    = "Shale (Trn)",
  "shale"                           = "Shale (Tr)",
  "greenstone"                      = "Greenstone (Jsv)",
  "serpentine"                      = "Serpentinite (Jsp)",
  "sci_schist"                      = "Schist",
  "schist_from_conglomerate"        = "Test Schist"
)


rock_class_map <- c(
  "gabbro_diorite"                   = "Igneous",
  "jolla_viejo_formation_sandstone" = "Sedimentary",
  "jolla_viejo_formation"           = "Sedimentary",
  "older_alluvium"                  = "Sedimentary",
  "vaqueros_formation_sandstone"    = "Sedimentary",
  "vaqueros_formation_conglomerate" = "Sedimentary",
  "monterey_formation"              = "Sedimentary",
  "tuff"                            = "Sedimentary",
  "cozy_dell_shale"                 = "Sedimentary",
  "rincon_shale"                    = "Sedimentary",
  "shale"                           = "Sedimentary",
  "greenstone"                      = "Metamorphic",
  "serpentine"                      = "Ultramafic",
  "sci_schist"                      = "Metamorphic",
  "schist_from_conglomerate"        = "Metamorphic"
)






rock_riley <- riley_rock_n |> 
  rename(n_ppm = nitrogen_ppm) |> 
  mutate(
    across(where(is.character), str_to_lower),
    location = "SCI",
    sample_name = str_replace(sample_id, "-[0-9]+$", ""),
    source = "Riley"
  )


samples <- rock_nitrogen |>
  clean_names() |>
  mutate(
    across(where(is.character), 
           ~ str_squish(.) |> str_replace_all(" ", "_") |> tolower()),
    soaked = case_when(
      str_detect(sample_id, "-p-") ~ "yes",
      str_detect(sample_id, "-n-") ~ "no",
      TRUE ~ NA
    ),
    sample_name = str_extract(sample_id, "(.*)-[pn]-"),
    location = if_else(str_detect(sample_name, "p1"), "Sedgwick", "SCI"),
    source = "samples"
  ) |>
  filter(soaked == "yes",
         sample_name != "ref_soil")


rock_all <- bind_rows(
  rock_riley |> 
    select(sample_id, rock_type, n_ppm, location, sample_name, source),

  samples |> 
    select(sample_id, rock_type, n_ppm, location, sample_name, source)
) 
  

rock_new <- rock_all %>%
  mutate(
    lithology = case_when(
      rock_type == "gabbro_diorite"                   ~ "Gabbro–Diorite",
      rock_type == "jolla_viejo_formation_sandstone" ~ "Sandstone (Tjv)",
      rock_type == "jolla_viejo_formation"           ~ "Sandstone (Tjv)",
      rock_type == "older_alluvium"                  ~ "Alluvium (Qoa)",
      rock_type == "vaqueros_formation_sandstone"    ~ "Sandstone (Tvs)",
      rock_type == "vaqueros_formation_conglomerate" ~ "Conglomerate (Tvs)",
      rock_type == "monterey_formation"              ~ "Mudstone/Shale (Tmo)",
      rock_type == "tuff"                            ~ "Tuff (Ttu)",
      rock_type == "cozy_dell_shale"                 ~ "Shale (Tcd)",
      rock_type == "rincon_shale"                    ~ "Shale (Trn)",
      rock_type == "shale"                           ~ "Shale (Tr)",
      rock_type == "greenstone"                      ~ "Greenstone (Jsv)",
      rock_type == "serpentine"                      ~ "Serpentinite (Jsp)",
      rock_type == "sci_schist"                      ~ "Schist",
      rock_type == "schist_from_conglomerate"        ~ "'Blue' Schist",
      TRUE ~ "Unknown"
    )
  )

rock_prep <- rock_new %>%
  mutate(
    rock_class = case_when(
      rock_type == "gabbro_diorite" ~ "Igneous",
      
      rock_type %in% c(
        "jolla_viejo_formation_sandstone",
        "jolla_viejo_formation",
        "older_alluvium",
        "vaqueros_formation_sandstone",
        "vaqueros_formation_conglomerate",
        "monterey_formation",
        "tuff",
        "cozy_dell_shale",
        "rincon_shale",
        "shale"
      ) ~ "Sedimentary",
      
      rock_type %in% c(
        "greenstone",
        "sci_schist",
        "schist_from_conglomerate"
      ) ~ "Metamorphic",
      
      rock_type == "serpentine" ~ "Ultramafic",
      
      TRUE ~ "Unknown"
    )
  )

rock_p <- rock_prep %>%
  rename(
    SampleID = sample_name,
    Lithology = lithology,
    Source = source,
    Location = location,
    RockClass = rock_class
  ) %>% 
  mutate(
    SampleID = str_extract(SampleID, "^[^-]+")
  )




table_rock <- rock_p |> 
  group_by(Location, Source) |> 
   distinct(SampleID, .keep_all = TRUE) |> 
  select(SampleID, Lithology, Source, Location, RockClass)



test <- flextable(table_rock)
print(test)
  



```

